services:
  - type: web
    name: gestion-financiera
    env: python
    buildCommand: bash build.sh
    startCommand: bash start.sh
    healthCheckPath: /healthz/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
